### ISSUE TITLE
add git download option for smithy model sources

### ISSUE THREAD

**Issue by stevelr** [wasmCloud/weld#57]
in `codegen.toml`, you can specify a smithy model dependency with either a file path or an http(s) url. A third and useful option would be to support a "git:" scheme to fetch a file from a github repo. 

A point of friction with the current two options is that if you have a `.smithy` file in one repo and want to generate code from it in another repo - as you might have with distributed development teams - the smithy file has to be copied into the static space of an http(s) server, or you need to publish the repo as github pages.

**Comment by stevelr** [comment]
Works already using `cdn.jsdelivr.net`.
You can even use a git commit id if you want:
```toml
[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces@50345db5db7796db50d16dd39834c6e5432bf808/core/wasmcloud-core.smithy"
```
